name: dog_emotion_app
description: Native Flutter dog emotion scanner for Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  file_picker: ^8.1.7
  flutter_tts: ^4.2.0
  image: ^4.5.2
  path_provider: ^2.1.5
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/Logo TItle.png
    - assets/images/Full Logo.png
    - assets/model.tflite
